/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MoneystreamDash {
        "debug": boolean;
        "showControls": boolean;
    }
    interface MoneystreamVideo {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLMoneystreamDashElement extends Components.MoneystreamDash, HTMLStencilElement {
    }
    var HTMLMoneystreamDashElement: {
        prototype: HTMLMoneystreamDashElement;
        new (): HTMLMoneystreamDashElement;
    };
    interface HTMLMoneystreamVideoElement extends Components.MoneystreamVideo, HTMLStencilElement {
    }
    var HTMLMoneystreamVideoElement: {
        prototype: HTMLMoneystreamVideoElement;
        new (): HTMLMoneystreamVideoElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "moneystream-dash": HTMLMoneystreamDashElement;
        "moneystream-video": HTMLMoneystreamVideoElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface MoneystreamDash {
        "debug"?: boolean;
        "showControls"?: boolean;
    }
    interface MoneystreamVideo {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "moneystream-dash": MoneystreamDash;
        "moneystream-video": MoneystreamVideo;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "moneystream-dash": LocalJSX.MoneystreamDash & JSXBase.HTMLAttributes<HTMLMoneystreamDashElement>;
            "moneystream-video": LocalJSX.MoneystreamVideo & JSXBase.HTMLAttributes<HTMLMoneystreamVideoElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
